### PR TITLE
BugFix: Hide calendar schedule banner on Server

### LINKED ISSUE #1178: BUG: Misleading banner in the Calendar view
**Bug Description**

When Calendar view is opened, there is a yellow banner "Reminder! The Prefect Scheduler will only schedule 10 runs in advance.":
https://github.com/PrefectHQ/ui/blob/89735d25de76377575c86e94c25774e644faafef/src/pages/Calendar/Calendar-Day.vue#L270

This is not true, if the `max_scheduled_runs_per_flow` flag is modified in towel, see: https://github.com/PrefectHQ/server/pull/281 - it's better to either hide the "warning" or expose the value so UI can access it and use in the banner.

**Steps To Reproduce**
1. Run Prefect Server with modified flag `max_scheduled_runs_per_flow` in towel to 24
2. Create a simple flow and schedule hourly
3. Run UI and go to Calendar view
4. The message will be displayed that only 10 runs are visible, but 24 runs will be visible in the calendar

**Browsers Tested:**
* [ ] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

----------
**Notes**

### PR DESCRIPTION
**Pull request by ThatGalNatalie**
## Description
<! -- What is it meant to do? -->
Hides the "Reminder! The Prefect Scheduler will only schedule 10 runs in advance" banner for users on Server

## Linked Issues
<! -- Use a key word (e.g. closes or resolves) to close related issues  -->
Resolves #1178 

## Tests and performance

 - [x] Changes to any .js files are covered by existing tests or this PR adds new tests (if not please explain why below)
 - [x] No new packages are added or package size and performance considerations are discussed below
 - [x] PR Title fits our [changelog format](https://github.com/PrefectHQ/ui#readme)

 ## Releases/Changelog cuts only
 - [ ] Completed the [QA Checklist](https://www.notion.so/prefect/Cloud-UI-QA-Checklist-038a5a5d40a249d78232917ad1b923b9) in staging

### CODE REVIEW

File: src/pages/Calendar/RunMenu.vue [hunk 1]
```diff
@@ -16,7 +17,15 @@ export default {
...
     active: { type: Boolean, required: true }
   },
-  computed: {},
+  computed: {
+    ...mapGetters('api', ['isCloud']),
+    showScheduleBanner() {
+      if (this.run.state === 'Scheduled' && this.active && this.isCloud) {
+        return true
+      }
+      return false
```
Comment (stackoverfloweth) [inline src/pages/Calendar/RunMenu.vue:26]: this can be written as just `return this.run.state === 'Scheduled' && this.active && this.isCloud`

**Review by stackoverfloweth — DISMISSED** [review]
looks good aside from just the 1 tiny suggestion
