### PR TITLE
Refetch task run states after flow run finishes

### LINKED ISSUE #369: BUG: Restarting from failed not setting task run back to scheduled
**Bug Description**
When restarting a flow run from failed the task run that was failed stays in a failed state and thus will not restart properly.

**Steps To Reproduce**

Flow:

```python
from prefect import task, Flow

@task
def fail():
    raise ValueError()

with Flow("Restart Me") as flow:
    fail()
```

First run logs:

```
[2020-10-22 21:37:02] INFO - prefect.CloudFlowRunner | Beginning Flow run for 'Restart Me'
[2020-10-22 21:37:02] DEBUG - prefect.CloudFlowRunner | Using executor type LocalExecutor
[2020-10-22 21:37:02] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Scheduled to Running
[2020-10-22 21:37:03] INFO - prefect.CloudTaskRunner | Task 'fail': Starting task run...
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Handling state change from Pending to Running
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Calling task.run() method...
[2020-10-22 21:37:03] ERROR - prefect.CloudTaskRunner | Unexpected error: ValueError()
Traceback (most recent call last):
  File "/Users/josh/Desktop/code/prefect/src/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/josh/Desktop/code/prefect/src/prefect/engine/task_runner.py", line 849, in get_task_run_state
    logger=self.logger,
  File "/Users/josh/Desktop/code/prefect/src/prefect/utilities/executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "restartme.py", line 22, in fail
    raise ValueError()
ValueError
[2020-10-22 21:37:03] DEBUG - prefect.CloudTaskRunner | Task 'fail': Handling state change from Running to Failed
[2020-10-22 21:37:03] INFO - prefect.CloudTaskRunner | Task 'fail': Finished task run for task with final state: 'Failed'
[2020-10-22 21:37:03] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2020-10-22 21:37:03] INFO - prefect.CloudFlowRunner | Flow run FAILED: some reference tasks failed.
[2020-10-22 21:37:03] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Running to Failed
```

Click `RESTART` button on flow run page.

Second run logs:

```
[2020-10-22 21:37:29] INFO - prefect.CloudFlowRunner | Beginning Flow run for 'Restart Me'
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Using executor type LocalExecutor
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Scheduled to Running
[2020-10-22 21:37:29] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2020-10-22 21:37:30] INFO - prefect.CloudFlowRunner | Flow run FAILED: some reference tasks failed.
[2020-10-22 21:37:30] DEBUG - prefect.CloudFlowRunner | Flow 'Restart Me': Handling state change from Running to Failed
```

In the logs we should be seeing that the `fail` task runs and the value error is raised again however that does not happen.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

### PR DESCRIPTION
**Pull request by zhen0**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
- Closes #369 and fixes a bug on restart from failed which was missing failed task runs
- Refetches the failed task run query after a flow run finishes (previously this was not catching failed task runs if the flow run page was not refreshed after running)

### CODE REVIEW

**Review by znicholasbrown — COMMENTED** [review]
@zhen0 might we want to refetch the `failedTaskRuns` every time the button is clicked? I can forsee a scenario where a run hasn't finished but still can be restarted.

**Comment by zhen0** [comment]
@znicholasbrown - We don't allow restarts until a flow run has entered a finished (failed or cancelled state) but I was on the fence about adding a refetch on button click anyway so I've added it in here.

File: src/pages/FlowRun/Actions.vue [hunk 1]
```diff
@@ -59,11 +59,18 @@ export default {
       if (oldVal.state === 'Scheduled' && newVal.state !== 'Scheduled') {
         this.isRunningNow = false
       }
+      if (FINISHED_STATES.includes(newVal.state)) {
```
Comment (znicholasbrown) [inline src/pages/FlowRun/Actions.vue:62]: I think to avoid excessive queries for finished runs we should check that `newVal` and `oldVal` are different:
 ```suggestion
      if (newVal.state !== oldVal.state && FINISHED_STATES.includes(newVal.state)) {
```

**Review by znicholasbrown — CHANGES_REQUESTED** [review]
Ah, good point @zhen0 - just one suggestion then in the watcher.

File: src/pages/FlowRun/Actions.vue (hunk 1 above)
Comment (zhen0) [reply src/pages/FlowRun/Actions.vue]: Good point - I've added.

Comment (znicholasbrown) [reply src/pages/FlowRun/Actions.vue]: Sorry, it looks like my suggestion caused a linting issue that's preventing the build 🤦

**Review by znicholasbrown — APPROVED** [review]
